### ISSUE TITLE
Roles

### ISSUE THREAD

**Issue by patagoniahiker** [tahmidrasif/Asp.Net-Mvc-Bootstrap#1]
Hi, does this have the GUI to manage roles and users fully implmented.

Are you using GUID or int for primary key.

Also can you share how to add roles from GUI dynamically to the controllers or actions, rather than putting it in the code.

**Comment by tahmidrasif** [comment]
No.... It's a initial commit with only 2 bootstrap control.... Still more to develop like ticker, real time crud and map control.... :)

**Comment by patagoniahiker** [comment]
Awesome, can you update with role / user management please. :+1: 

BTW, how can I manage roles inside a group (like nested group). For managers inside coca cola, vs mangers inside Pepsi

**Comment by tahmidrasif** [comment]
Please watch this videos. Every thing will be cleared. Sorry for the late... :(

https://www.youtube.com/watch?v=CnX1cfDA_oY&index=28&list=PLWrHdon6qnTYvXgy0DnAjJwyjT1zI-Tcy

https://www.youtube.com/watch?v=VOf-Avs791g&list=PLWrHdon6qnTYvXgy0DnAjJwyjT1zI-Tcy&index=29

https://www.youtube.com/watch?v=v_dY2XfLfdk&list=PLWrHdon6qnTYvXgy0DnAjJwyjT1zI-Tcy&index=30

https://www.youtube.com/watch?v=ear_AcCVdx8&index=31&list=PLWrHdon6qnTYvXgy0DnAjJwyjT1zI-Tcy
